# Generated by Django 4.1.2 on 2022-12-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(help_text='Enter a language of the book (e.g Portuguese)', max_length=50),
        ),
    ]
